# Rust formatting configuration
# Using stable-friendly options only

# Basic formatting
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
edition = "2021"

# Line width
max_width = 100
use_small_heuristics = "Default"

# Imports
reorder_imports = true
reorder_modules = true

# Other
use_field_init_shorthand = true
use_try_shorthand = true